# Generated by Django 3.0.3 on 2020-03-03 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200303_1911'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
