# Generated by Django 3.0.3 on 2020-03-03 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200303_1915'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
