# Generated by Django 3.0.3 on 2020-03-03 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20200303_1918'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
