# Generated by Django 3.0.3 on 2020-03-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20200303_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quality_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
