# Generated by Django 3.0.3 on 2020-03-03 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_product_quality_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quality_percentage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
    ]
